# Generated by Django 5.0.1 on 2024-02-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_smartphones_image_alter_smartphones_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Smartphones',
        ),
    ]
