# Generated by Django 5.0.1 on 2024-02-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_smartphone_delete_smartphones'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
