# Generated by Django 5.0.1 on 2024-02-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_smartphone_data_alter_smartphone_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='data',
            new_name='date',
        ),
    ]
