# Generated by Django 5.0.1 on 2024-02-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_data_smartphone_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='aspect_ratio',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='clock_frequency',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='number_of_cores',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='panel_type',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='pixel_density',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='resolution',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='update_frequency',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
